dist: xenial
language: java
jdk:
  - oraclejdk11

services:
  - mysql

branches:
  only:
    - main

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS notes;'
script:
  - ./gradlew check
  - ./gradlew install -x check
  - ./gradlew codeCoverageReport --continue
after_success:
  bash <(curl -s https://codecov.io/bash)