spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/notes?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver